# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/glossary.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pp/glossary.proto\x12\ndictionary\"\x07\n\x05\x45mpty\"4\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\",\n\tTermsList\x12\x1f\n\x05terms\x18\x01 \x03(\x0b\x32\x10.dictionary.Term\"\x1f\n\x0fTermNameRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xad\x02\n\x0fGlossaryService\x12\x37\n\x0bGetAllTerms\x12\x11.dictionary.Empty\x1a\x15.dictionary.TermsList\x12-\n\x07\x41\x64\x64Term\x12\x10.dictionary.Term\x1a\x10.dictionary.Term\x12\x38\n\x07GetTerm\x12\x1b.dictionary.TermNameRequest\x1a\x10.dictionary.Term\x12\x30\n\nUpdateTerm\x12\x10.dictionary.Term\x1a\x10.dictionary.Term\x12\x46\n\nDeleteTerm\x12\x1b.dictionary.TermNameRequest\x1a\x1b.dictionary.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.glossary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_TERM']._serialized_start=43
  _globals['_TERM']._serialized_end=95
  _globals['_TERMSLIST']._serialized_start=97
  _globals['_TERMSLIST']._serialized_end=141
  _globals['_TERMNAMEREQUEST']._serialized_start=143
  _globals['_TERMNAMEREQUEST']._serialized_end=174
  _globals['_MESSAGERESPONSE']._serialized_start=176
  _globals['_MESSAGERESPONSE']._serialized_end=210
  _globals['_GLOSSARYSERVICE']._serialized_start=213
  _globals['_GLOSSARYSERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
