# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app import glossary_pb2 as app_dot_glossary__pb2


class GlossaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTerms = channel.unary_unary(
                '/dictionary.GlossaryService/GetAllTerms',
                request_serializer=app_dot_glossary__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.TermsList.FromString,
                )
        self.AddTerm = channel.unary_unary(
                '/dictionary.GlossaryService/AddTerm',
                request_serializer=app_dot_glossary__pb2.Term.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.Term.FromString,
                )
        self.GetTerm = channel.unary_unary(
                '/dictionary.GlossaryService/GetTerm',
                request_serializer=app_dot_glossary__pb2.TermNameRequest.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.Term.FromString,
                )
        self.UpdateTerm = channel.unary_unary(
                '/dictionary.GlossaryService/UpdateTerm',
                request_serializer=app_dot_glossary__pb2.Term.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.Term.FromString,
                )
        self.DeleteTerm = channel.unary_unary(
                '/dictionary.GlossaryService/DeleteTerm',
                request_serializer=app_dot_glossary__pb2.TermNameRequest.SerializeToString,
                response_deserializer=app_dot_glossary__pb2.MessageResponse.FromString,
                )


class GlossaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTerms,
                    request_deserializer=app_dot_glossary__pb2.Empty.FromString,
                    response_serializer=app_dot_glossary__pb2.TermsList.SerializeToString,
            ),
            'AddTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTerm,
                    request_deserializer=app_dot_glossary__pb2.Term.FromString,
                    response_serializer=app_dot_glossary__pb2.Term.SerializeToString,
            ),
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=app_dot_glossary__pb2.TermNameRequest.FromString,
                    response_serializer=app_dot_glossary__pb2.Term.SerializeToString,
            ),
            'UpdateTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTerm,
                    request_deserializer=app_dot_glossary__pb2.Term.FromString,
                    response_serializer=app_dot_glossary__pb2.Term.SerializeToString,
            ),
            'DeleteTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTerm,
                    request_deserializer=app_dot_glossary__pb2.TermNameRequest.FromString,
                    response_serializer=app_dot_glossary__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictionary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dictionary.GlossaryService/GetAllTerms',
            app_dot_glossary__pb2.Empty.SerializeToString,
            app_dot_glossary__pb2.TermsList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dictionary.GlossaryService/AddTerm',
            app_dot_glossary__pb2.Term.SerializeToString,
            app_dot_glossary__pb2.Term.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dictionary.GlossaryService/GetTerm',
            app_dot_glossary__pb2.TermNameRequest.SerializeToString,
            app_dot_glossary__pb2.Term.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dictionary.GlossaryService/UpdateTerm',
            app_dot_glossary__pb2.Term.SerializeToString,
            app_dot_glossary__pb2.Term.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dictionary.GlossaryService/DeleteTerm',
            app_dot_glossary__pb2.TermNameRequest.SerializeToString,
            app_dot_glossary__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
